Update SSH key references and enhance envrc functionality for GitHub setup

diff --git a/rc/envrc b/rc/envrc
--- a/rc/envrc
+++ b/rc/envrc
@@ -11,7 +11,7 @@ envrc-generate() {
     echo "📂 Created .env folder in $HOME/.env (if it didn't already exist)"
 
     # Softlink all files from the .env folder in this repository into the destination .env folder
-    for file in $(find "$SOURCE_ENV_FOLDER" -type f); do
+    for file in $(find "$SOURCE_ENV_FOLDER" -type f | sort); do
         ln -sf "$file" "$ENV_FOLDER/$(basename $file)"
         echo "🔗 Softlinked '$file' to '$ENV_FOLDER/$(basename $file)'"
     done
@@ -23,14 +23,17 @@ envrc-generate() {
     echo "📝 Created '$ENV_RC' with a warning message"
 
     if [ -n "$(ls -A $ENV_FOLDER/)" ]; then
-        if [ -n "$(ls -A $ENV_FOLDER/ 2>/dev/null)" ]; then
-            cat "$ENV_FOLDER/"* >> "$ENV_RC"
-        else
-            echo "No files to concatenate in $ENV_FOLDER/"
-        fi
-        echo "📄 Concatenated all files from $ENV_FOLDER/ into '$ENV_RC'"
+        for file in $(find "$SOURCE_ENV_FOLDER" -type f | sort); do
+            cat "$file" >> "$ENV_RC"
+            echo "➕ Appended '$file' to '$ENV_RC'"
+        done
+        echo "📄 Concatenated all files from $SOURCE_ENV_FOLDER/ into '$ENV_RC'"
     fi
-    echo "✅ You may now run 'source ~/.envrc'"
+    echo "✅ You may now run 'source ~/.env/envrc'"
 }
 
-source "$HOME/.env/envrc" || echo "Failed to source ~/.envrc ; Did you forget to run envrc-generate?"
+envrc-source() {
+    source "$HOME/.env/envrc" || echo "Failed to source ~/.env/envrc ; Did you forget to run envrc-generate?"
+}
+
+envrc-source
